- name: variables from promt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your name?
    private: false
  - name: password
    prompt: what is your name?
    private: true
  tasks:
  - name: print creditials
    ansible.builtin.debug:
      msg: "hello user nmae is {{ username }} , password is {{ password }}"

