- name: "variables from files"
  hosts: local
  connection: local
  tasks:
  - name: "print course name"
    ansible.builtin.debug:
      msg: "course is {{ course }}  duration is {{ duration }} trainer is {{ trainer }}"